#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=ACM | grep "^app\/media\/js\/.*.js$")

echo $files | xargs ./node_modules/.bin/eslint

rc=$?
if [[ $rc != 0 ]] ; then
	echo "ESLint check failed, commit denied"
	exit $rc
fi

git diff --cached --name-only --diff-filter=ACM | if grep "app/jspm.config.js"
then
	./node_modules/.bin/jspm unbundle
	git add app/jspm.config.js
fi
