#!/bin/bash

git diff --cached --name-only --diff-filter=ACM | grep "^app\/media\/js\/.*.js$" | xargs ./node_modules/.bin/eslint
git diff --cached --name-only --diff-filter=ACM | grep "^app\/jspm\.config\.js$" | ./node_modules/.bin/jspm unbundle && git add app/jspm.config.js
